package main

import _func "example/func"

func main() {
	//_func.Hello()
	//_func.Values()
	//_func.Variables()
	//_func.Constants()
	//_func.For()
	//_func.IfElse()
	//_func.Switch()
	//_func.Array()
	//_func.Slice()
	//_func.Map()
	//_func.Map1()
	//_func.Functions()
	//_func.MultipleReturnValues()
	//_func.VariadicFunctions()
	//_func.Closures()
	//_func.Closures1()
	//_func.Recursion()
	//_func.RangeOverBuiltInTypes()
	//_func.Pointer()
	//_func.StringsAndRunes()
	//_func.Structs()
	//_func.Methods()
	//_func.Interfaces()
	//_func.Enums()
	//_func.Generics()
	//_func.SingleValueIterator()
	//_func.KeyValueIterator()
	//_func.FibonacciIterator()
	//_func.Errors()
	//_func.CustomErrors()

	//_func.Goroutines()
	//action.Goroutines()
	//action.Goroutines4()
	//action.Goroutines9()
	//action.Goroutines13()
	//action.Goroutines15()
	//action.GoroutineMutex()
	//action.GoroutineChan1()
	//action.GoroutineChan2()
	//action.GoroutineChan2Fixed()
	//action.GoroutineChanBuffer()

	//_func.Channels()
	//_func.ChannelBuffering()
	//_func.ChannelBuffer2()
	//_func.ChannelSynchronization1()
	//_func.ChannelSynchronization2()
	//_func.ChannelSynchronization3()
	//_func.ChannelDirections()
	//_func.ChannelSelect()
	//_func.ChannelSelect1()
	//_func.ChannelSelect2()
	//_func.ChannelSelect3()
	//_func.ChannelTimeout()
	//_func.ChannelNonBlockingOperations()
	//_func.ChannelClose()
	//_func.ChannelRangeOver()
	//_func.Timers()
	//_func.Tickers()
	//_func.WorkPools()
	//_func.WaitGroups()
	//_func.RateLimiting()
	//_func.AtomicCounters()
	//_func.Mutexes()
	_func.StatefulGoroutines()
}
